[build]
publish = 'public'
command = "npm install && hugo --gc --minify"

[build.environment]
HUGO_VERSION = '0.163.3'
NODE_VERSION = '20'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
